name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore WinFlipped.csproj

    - name: Build
      run: dotnet build WinFlipped.csproj --configuration ${{ matrix.configuration }} --no-restore

    - name: Publish
      run: dotnet publish WinFlipped.csproj --configuration ${{ matrix.configuration }} --runtime win-x64 --self-contained true -p:PublishSingleFile=true --output publish\${{ matrix.configuration }}

    - name: Create ZIP archive
      run: Compress-Archive -Path publish\${{ matrix.configuration }}\* -DestinationPath WinFlipped-${{ github.event.release.tag_name }}-${{ matrix.configuration }}.zip

    - name: Upload release asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ github.event.release.tag_name }} WinFlipped-${{ github.event.release.tag_name }}-${{ matrix.configuration }}.zip --clobber
